### ISSUE TITLE
ISSUE IN EQUEUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/E-QUEUE#2]
DEFECT OWNER: PUNI

![issue_03082015](https://cloud.githubusercontent.com/assets/9882142/9031640/1902b392-39d3-11e5-812c-5a2e3a1e4c72.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
DEFECT OWNER: PUNI,


ALL FORM AND DT SHLD BE RESPONSIVE. ALREADY TOLD THIS ONE CLIENT WILL USE IN TAB.

THIS IS THE MAIN REQUIRMENT, NOW VIEW BRANCH DT NOT RESPONSIVE, 

2. HOW TO EDIT THE  SMS TEMPLATE , ADMIN CANNT EDIT NOW

3. AFTER CREATED USER, CANNT LOAD IN THE VIEW BRANCH DT. AFTER LOGOUT ONLY LOADING.

4. PUT SOME DUMMY LOGO IN LOGIN PAGE.

5.AFTER NOTIFY WHY SHOWING SMS TEMPLATE MSG TO ADMIN, SHLD BE SUCCESSFULY SMS SENT / NOT LIKE THAT USE

6. IMPLEMENT  THEME/BG COLOR

CLEAR ALL THEN ONLY CAN SEND TO CLIENT. ALREADY DELAYED.

**Comment by DHANDAPANISATTANATHAN** [comment]
DEFECT OWNER: PUNI

FIX THE BELOW ISSUE:

![issue_17082015](https://cloud.githubusercontent.com/assets/9882142/9307571/c01b635e-4531-11e5-8121-8c77d8102794.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
@Archana20 

Where is the defect list? I need all defect list immediately in this tracker. Open it.

**Comment by Archana20** [comment]
Sn Sir

My wifi was not working it is asking for Admin pw..so will do it in some
time ..

Arc

**Comment by DHANDAPANISATTANATHAN** [comment]
@Archana20 

No, Send me the details via mail to me. I ll update

**Comment by Archana20** [comment]
Ok sir
I will send in an hour
Arc

**Comment by Archana20** [comment]
![alignment defect 1](https://cloud.githubusercontent.com/assets/13703309/9753520/9ac1182c-56db-11e5-94c5-6ffbac9d72fa.png)
![alignment defect](https://cloud.githubusercontent.com/assets/13703309/9753522/9ac740e4-56db-11e5-9ae1-f1af6031a328.png)
![alignment defect2](https://cloud.githubusercontent.com/assets/13703309/9753521/9ac401e0-56db-11e5-9a8d-ef72dc4eee15.png)
![equeue defect](https://cloud.githubusercontent.com/assets/13703309/9753523/9ac77ac8-56db-11e5-82d9-5d4dcde68d90.png)

**Comment by Archana20** [comment]
![alignment defect 1](https://cloud.githubusercontent.com/assets/13703309/9753817/78c503ce-56df-11e5-866f-ead28d5a5eb4.png)

Alignment Defect .

**Comment by Archana20** [comment]
![alignment defect 2](https://cloud.githubusercontent.com/assets/13703309/9753821/87a2e5d2-56df-11e5-8e0f-46ef2ae80c47.png)

Alignment need to be changed

**Comment by Archana20** [comment]
![branch defect](https://cloud.githubusercontent.com/assets/13703309/9753831/931a98c4-56df-11e5-9338-7c7e510fbe86.png)

when i select Arccc particular branch ..it pulls up all the branch details. But when i select Test it pulls up only Test Branch details.That has to be rectified.

**Comment by Archana20** [comment]
![sms status defect](https://cloud.githubusercontent.com/assets/13703309/9753855/c6eb1d04-56df-11e5-838a-82266be491dd.png)

When i pull up SMS Status and pull up Arcc Branch Status again it pull up all the branch SMS Status.Need to be rectified.

**Comment by Archana20** [comment]
![defect equeue](https://cloud.githubusercontent.com/assets/13703309/9785138/a71a45a6-57cd-11e5-9c01-d583f2794f05.png)

Sn Sir
 I have clearly mentioned all the defects and everything is in one page. If anything else let me know.

**Comment by punithavimalraj** [comment]
label alignment for mandatory field changed n updated in gce.

SMS status n view branch showing correctly , if u have any doubt chk with DIVYA.
